Resolve "simplify cicd install scripts"

diff --git a/test/integration/define-env b/test/integration/define-env
--- a/test/integration/define-env
+++ b/test/integration/define-env
@@ -1,8 +1,14 @@
 #!/usr/bin/env bash
 
+# This script defines variables constructed from other variables, in order to
+# keep the number of configured variables to a minimum, and to
+# keep the variable definitions largely in one place.
+# Deployment scripts shall source this file.
+
+
+## VALIDATE INPUT VARS
 ## print list of all missing vars (instead of exiting on first undefined var)
 ## exit with 1 if any vars are missing; 0 otherwise
-
 REQUIRED_VARS="
 JAWS_SITE
 DEPLOYMENT_NAME
@@ -21,74 +27,90 @@ for VAR in $REQUIRED_VARS; do
     echo "Missing env var: $VAR">&2
     RESULT=1
   fi
+  echo "... $VAR : OK"
 done
 [ $RESULT -eq 0 ] || exit $RESULT
 
 
-# These are variables constructed from other variables, in order to
-# keep the number of configured variables to a minimum, and to
-# keep the variable definitions largely in one place.
-# Deployment scripts shall source this file.
-
+## DEPLOYMENT-SPECIFIC VARIABLES
+echo "DEFINING DEPLOYMENT VARS"
 function set_deployment_var {
   VAR_NAME="$1"
   SRC_VAR_NAME="${DEPLOYMENT_NAME}_${VAR_NAME}"
+  if [ -z ${!SRC_VAR_NAME+xxx} ]; then
+    echo "Missing env var: $SRC_VAR_NAME">&2
+    exit 1
+  fi
   VALUE="${!SRC_VAR_NAME}"
   echo "... $VAR_NAME"
   export $VAR_NAME
   printf -v "$VAR_NAME" "%s" "$VALUE"
 }
+DEPLOYMENT_VARS="
+LOG_LEVEL
+JAWS_SUPERVISOR_PORT
+JTM_SUPERVISOR_PORT
+JAWS_AUTH_PORT
+JAWS_REST_PORT
+CROMWELL_PORT"
+for DEPLOYMENT_VAR in $DEPLOYMENT_VARS; do
+  set_deployment_var $DEPLOYMENT_VAR
+done
 
-## DEPLOYMENT-SPECIFIC VARIABLES:
-echo "DEFINING DEPLOYMENT VARS"
-set_deployment_var "LOG_LEVEL"
-set_deployment_var "JAWS_SUPERVISOR_PORT"
-set_deployment_var "JTM_SUPERVISOR_PORT"
-set_deployment_var "JAWS_AUTH_PORT"
-set_deployment_var "JAWS_REST_PORT"
-set_deployment_var "CROMWELL_PORT"
 
+## SITE-SPECIFIC VARIABLES:
+## This will define global vars with a SITE_ prefix, with values from variables referenced by the JAWS_SITE
+## variable.  For instance, if JAWS_SITE="JGI", setting GLOBUS_EP site var will define a SITE_GLOBUS_EP var
+## with the value from JGI_GLOBUS_EP.  
+## This allows the site installation scripts to use the SITE_* vars.
+echo "DEFINING SITE VARS"
 function set_site_var {
   VAR_NAME="$1"
   SRC_VAR_NAME="${JAWS_SITE}_${VAR_NAME}"
+  if [ -z ${!SRC_VAR_NAME+xxx} ]; then
+    echo "Missing env var: $SRC_VAR_NAME">&2
+    exit 1
+  fi
   SITE_VAR_NAME="SITE_${VAR_NAME}"
   VALUE="${!SRC_VAR_NAME}"
   echo "... $SITE_VAR_NAME"
   export $SITE_VAR_NAME
   printf -v "$SITE_VAR_NAME" "%s" "$VALUE"
 }
+SITE_VARS="
+INSTALL_BASEDIR
+GLOBUS_EP
+GLOBUS_ROOT_DIR
+GLOBUS_DEFAULT_DIR
+RMQ_HOST
+RMQ_PORT
+PYTHON
+PYTHON_PIP
+LOAD_PYTHON
+JAWS_GROUP
+JTM_GROUP
+CLIENT_GROUP
+JAWS_SCRATCH_BASEDIR
+JTM_SCRATCH_BASEDIR
+JAWS_SW_BASEDIR
+JTM_SW_BASEDIR
+REF_DATA_DIR
+SUPERVISOR_HOST
+CONTAINER_TYPE
+DB_HOST
+DB_PORT
+CLUSTER_QOS
+CLUSTER_PARTITION
+CLUSTER_ACCOUNT
+CLUSTER_CONSTRAINT
+MAX_RAM_GB
+RMQ_PW
+DB_PW
+LOAD_JAVA"
+for SITE_VAR in $SITE_VARS; do
+  set_site_var $SITE_VAR
+done
 
-## SITE-SPECIFIC VARIABLES:
-echo "DEFINING SITE VARS"
-set_site_var "INSTALL_BASEDIR"
-set_site_var "GLOBUS_EP"
-set_site_var "GLOBUS_ROOT_DIR"
-set_site_var "GLOBUS_DEFAULT_DIR"
-set_site_var "RMQ_HOST"
-set_site_var "RMQ_PORT"
-set_site_var "PYTHON"
-set_site_var "PYTHON_PIP"
-set_site_var "LOAD_PYTHON"
-set_site_var "JAWS_GROUP"
-set_site_var "JTM_GROUP"
-set_site_var "CLIENT_GROUP"
-set_site_var "JAWS_SCRATCH_BASEDIR"
-set_site_var "JTM_SCRATCH_BASEDIR"
-set_site_var "JAWS_SW_BASEDIR"
-set_site_var "JTM_SW_BASEDIR"
-set_site_var "REF_DATA_DIR"
-set_site_var "SUPERVISOR_HOST"
-set_site_var "CONTAINER_TYPE"
-set_site_var "DB_HOST"
-set_site_var "DB_PORT"
-set_site_var "CLUSTER_QOS"
-set_site_var "CLUSTER_PARTITION"
-set_site_var "CLUSTER_ACCOUNT"
-set_site_var "CLUSTER_CONSTRAINT"
-set_site_var "MAX_RAM_GB"
-set_site_var "RMQ_PW"
-set_site_var "DB_PW"
-set_site_var "LOAD_JAVA"
 
 ## DEFINE VARS FROM OTHER VARS
 echo "DEFINING PATHS"
@@ -98,15 +120,23 @@ export SHIM_DIR="$INSTALL_DIR/shims"
 export LOGS_DIR="$INSTALL_DIR/logs"
 export SUPERVISOR_DIR="$SITE_INSTALL_BASEDIR/jaws-supervisord-$DEPLOYMENT_NAME"
 export SITE_CLIENT_INSTALL_DIR="$SITE_JAWS_SW_BASEDIR/jaws-$DEPLOYMENT_NAME"
-export SITE_CONTAINERS_DIR="$SITE_JTM_SCRATCH_BASEDIR/${SITE_CONTAINER_TYPE}_files"
 export SITE_JAWS_SCRATCH_DIR="$SITE_JAWS_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
 export SITE_JTM_SCRATCH_DIR="$SITE_JTM_SCRATCH_BASEDIR/jaws-$DEPLOYMENT_NAME"
 export SITE_JTM_WORKER_INSTALL_DIR="$SITE_JTM_SW_BASEDIR/jaws-worker-$DEPLOYMENT_NAME"
-export SITE_CROMWELL_JAR="$SITE_JAWS_SW_BASEDIR/cromwell/cromwell-$CROMWELL_VERSION.jar"
-export SITE_WOMTOOL_JAR="$SITE_JAWS_SW_BASEDIR/cromwell/womtool-$CROMWELL_VERSION.jar"
+# Globus-related dirs:
 export SITE_CROMWELL_TMPDIR="$INSTALL_DIR/cromwell-tmp"
 export SITE_UPLOADS_DIR="$SITE_JTM_SCRATCH_DIR/uploads"
 export SITE_DOWNLOADS_DIR="$SITE_JAWS_SCRATCH_DIR/downloads"
+# Cromwell-related dirs
+export SITE_CROMWELL_JAR="$SITE_JAWS_SW_BASEDIR/cromwell/cromwell-$CROMWELL_VERSION.jar"
+export SITE_WOMTOOL_JAR="$SITE_JAWS_SW_BASEDIR/cromwell/womtool-$CROMWELL_VERSION.jar"
+export SITE_CONTAINERS_DIR="$SITE_JTM_SCRATCH_BASEDIR/${SITE_CONTAINER_TYPE}_files"
+export CROMWELL_TMPDIR="$INSTALL_DIR/cromwell-tmp"
+export CROMWELL_WORKFLOW_LOGS_DIR="$LOGS_DIR/cromwell-workflow-logs"
+export CROMWELL_EXECUTIONS_DIR="$SITE_JTM_SCRATCH_DIR/cromwell-executions"
+export JTM_CONFIG_FILE="$SITE_JTM_WORKER_INSTALL_DIR/jaws-jtm.conf"
+export INSTALLED_CROMWELL_JAR="$INSTALL_DIR/cromwell.jar"
+# Globus has some rules about how paths are interpreted, depending on how the endpoing is configured.
 [[ ${SITE_GLOBUS_ROOT_DIR: -1} == "/" ]] || SITE_GLOBUS_ROOT_DIR="$SITE_GLOBUS_ROOT_DIR/"
 if [[ $SITE_GLOBUS_ROOT_DIR == "/" ]]; then
   export SITE_UPLOADS_SUBDIR=$SITE_UPLOADS_DIR
@@ -116,13 +146,18 @@ else
   export SITE_DOWNLOADS_SUBDIR=${SITE_DOWNLOADS_DIR#$SITE_GLOBUS_ROOT_DIR}
 fi
 
-## CREATE DIRS
+
+## CREATE DIRS AND SET GROUP AND PERMISSIONS
+## - there are expected to be "jaws" and "jtm" users
+## - "jaws" user belongs to "jaws" and "jtm" groups
+## - "jtm" user belongs to "jtm" group and no others for security purposes
+## - users don't belong to either "jaws" or "jtm" groups (protected)
 function setup_dir {
   local DIR="$1"
   local GROUP="$2"
   [[ -z $DIR ]] && echo "missing DIR" && exit 1
   [[ -z $GROUP ]] && echo "missing GROUP" && exit 1
-  echo "...$DIR $GROUP"
+  echo "... $DIR"
   test -d "$DIR" || mkdir -p "$DIR"
   chgrp "$GROUP" "$DIR"
   chmod 770 "$DIR"
@@ -138,6 +173,9 @@ SITE_CONTAINERS_DIR
 SITE_JAWS_SCRATCH_DIR
 SITE_JTM_WORKER_INSTALL_DIR
 SITE_CROMWELL_TMPDIR
+CROMWELL_TMPDIR
+CROMWELL_WORKFLOW_LOGS_DIR
+CROMWELL_EXECUTIONS_DIR
 "
 for DIR in $INSTALL_DIRS; do
   setup_dir "${!DIR}" "$SITE_JTM_GROUP"
diff --git a/test/integration/deploy-supervisord b/test/integration/deploy-supervisord
--- a/test/integration/deploy-supervisord
+++ b/test/integration/deploy-supervisord
@@ -1,7 +1,41 @@
 #!/usr/bin/env bash
 
-## VALIDATE AND SETUP ENV
-source ./test/integration/define-env
+echo "BEGIN deploy-supervisord"
+
+## VERIFY REQUIRED VARS ARE DEFINED
+# If any env are undefined, try sourcing the setup script and check again.
+# Exits if any required var is undefined.
+REQUIRED_VARS="
+SUPERVISOR_DIR
+SITE_PYTHON
+SITE_PYTHON_PIP
+SITE_JAWS_GROUP
+SITE_JTM_GROUP
+DEPLOYMENT_NAME
+SHIM_DIR
+JAWS_SUPERVISORD_PW
+JAWS_SUPERVISOR_PORT
+JTM_SUPERVISOR_PORT
+"
+RESULT=0
+for VAR in $REQUIRED_VARS; do
+  if [ -z ${!VAR+xxx} ]; then
+    echo "Missing env var, $VAR; sourcing setup script..."
+    source ./test/integration/define-env
+    RESULT=1
+    break
+  fi
+done
+if [[ $RESULT -ne 0 ]]; then
+  RESULT=0
+  for VAR in $REQUIRED_VARS; do
+    if [ -z ${!VAR+xxx} ]; then
+      echo "Missing env var: $VAR">&2
+      RESULT=1
+    fi
+  done
+fi
+[ $RESULT -eq 0 ] || exit 1
 
 ## CREATE DIRS
 test -d $SUPERVISOR_DIR || mkdir $SUPERVISOR_DIR
@@ -216,3 +250,5 @@ chgrp "$SITE_JAWS_GROUP" "$SUPERVISOR_DIR/supervisord-jaws.conf"
 chmod 660 "$SUPERVISOR_DIR/supervisord-jaws.conf"
 chgrp "$SITE_JTM_GROUP" "$SUPERVISOR_DIR/supervisord-jtm.conf"
 chmod 660 "$SUPERVISOR_DIR/supervisord-jtm.conf"
+
+printf "END deploy-supervisord\n\n"
diff --git a/test/integration/generate-shims b/test/integration/generate-shims
--- a/test/integration/generate-shims
+++ b/test/integration/generate-shims
@@ -1,26 +1,45 @@
 #!/usr/bin/env bash
 
+echo "BEGIN generate-shims"
+
 # NOTE: generate-shims should be run after generate-venvs
 
-source ./test/integration/define-env
+## VERIFY REQUIRED VARS ARE DEFINED
+# If any env are undefined, try sourcing the setup script and check again.
+# Exits if any required var is undefined.
+REQUIRED_VARS="
+DEPLOYMENT_NAME
+INSTALL_DIR
+SITE_JTM_WORKER_INSTALL_DIR
+SITE_JTM_SCRATCH_DIR
+SITE_JTM_GROUP
+SITE_JAWS_GROUP
+SITE_REF_DATA_DIR
+LOG_LEVEL
+SITE_CONTAINER_TYPE
+SITE_CROMWELL_TMPDIR
+SITE_LOAD_JAVA
+"
+RESULT=0
+for VAR in $REQUIRED_VARS; do
+  if [ -z ${!VAR+xxx} ]; then
+    echo "Missing env var, $VAR; sourcing setup script..."
+    source ./test/integration/define-env
+    RESULT=1
+    break
+  fi
+done
+if [[ $RESULT -ne 0 ]]; then
+  RESULT=0
+  for VAR in $REQUIRED_VARS; do
+    if [ -z ${!VAR+xxx} ]; then
+      echo "Missing env var: $VAR">&2
+      RESULT=1
+    fi
+  done
+fi
+[ $RESULT -eq 0 ] || exit 1
 
-## VALIDATE ENVS
-[[ -z $DEPLOYMENT_NAME ]]              && { printf "Missing DEPLOYMENT_NAME variable.\n"; exit 1; }
-[[ -z $INSTALL_DIR ]]                  && { printf "Missing INSTALL_DIR variable.\n"; exit 1; }
-[[ -z $SITE_JTM_WORKER_INSTALL_DIR ]]  && { printf "Missing JTM_WORKER_INSTALL_DIR variable.\n"; exit 1; }
-[[ -z $SITE_JTM_SCRATCH_DIR ]]         && { printf "Missing JTM_SCRATCH_DIR variable.\n"; exit 1; }
-[[ -z $SITE_JTM_GROUP ]]               && { printf "Missing SITE_JTM_GROUP variable.\n"; exit 1; }
-[[ -z $SITE_JAWS_GROUP ]]              && { printf "Missing SITE_JAWS_GROUP variable.\n"; exit 1; }
-[[ -z $SITE_REF_DATA_DIR ]]            && { printf "Missing REF_DATA_DIR variable.\n"; exit 1; }
-[[ -z $LOG_LEVEL ]]                    && { printf "Missing LOG_LEVEL variable.\n"; exit 1; }
-[[ -z $SITE_CONTAINER_TYPE ]]          && { printf "Missing CONTAINER_TYPE variable.\n"; exit 1; }
-[[ -z $SITE_CROMWELL_TMPDIR ]]         && { printf "Missing SITE_CROMWELL_TMPDIR variable.\n"; exit 1; }
-[[ -z $SITE_LOAD_JAVA ]]               && { printf "Missing SITE_LOAD_JAVA variable.\n"; exit 1; }
-
-## CREATE DIRS
-test -d $SITE_JTM_WORKER_INSTALL_DIR || mkdir $SITE_JTM_WORKER_INSTALL_DIR
-# chgrp doesn't work with parallel fs; see .gitlab-ci.yml for more info
-#chgrp $SITE_JTM_GROUP $SITE_JTM_WORKER_INSTALL_DIR
 
 ## WRITE SHIM SCRIPTS
 cat <<EOM > $SHIM_DIR/jaws-site-daemon-$DEPLOYMENT_NAME
@@ -96,3 +115,5 @@ EOM
 chgrp "$SITE_JTM_GROUP" "$SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME"
 chgrp "$SITE_JTM_GROUP" "$SHIM_DIR/jaws-deploy-worker-$DEPLOYMENT_NAME"
 chmod +x "$SHIM_DIR"/*
+
+printf "END generate-shims\n\n"
