added shanes code

diff --git a/test/integration/deploy-cromwell b/test/integration/deploy-cromwell
--- a/test/integration/deploy-cromwell
+++ b/test/integration/deploy-cromwell
@@ -68,10 +68,10 @@ chgrp "$SITE_JTM_GROUP" "$SITE_CROMWELL_JAR"
 # When creating the wrapper scripts the arguments to each script are as follows:
 # For SHIFTER
 # $1 image name
-# $2 shell name (eg - bash, csh)
-# $3 script name
-# $4 the location of the refdata directory location at the site
-# $5 the name of the directory $SITE_REF_DATA_DIR will be mounted on inside container
+# $2 the location of the refdata directory location at the site
+# $3 the name of the directory $SITE_REF_DATA_DIR will be mounted inside container
+# $4 shell name (eg - bash, csh)
+# $5 script name
 #
 # For SINGULARITY
 # $1 the location of the refdata directory location at the site
@@ -96,11 +96,70 @@ fi
 "
   CONTAINER_WRAPPER="$INSTALL_DIR/shifter_exec.sh"
   CONTAINER_EXEC_COMMAND="$CONTAINER_WRAPPER \${docker} $SITE_REF_DATA_DIR /refdata \${job_shell} \${script}"
-  cat <<EOM > "$CONTAINER_WRAPPER"
-#!/usr/bin/env bash
-echo \"Executing on \$HOSTNAME\" 1>&2
-exec shifter --image=\$1 -V \$2:\$3 \$4 \$5
-EOM
+  cat <<-"EOM" > "$CONTAINER_WRAPPER"
+  #!/usr/bin/env bash
+  echo "Executing on $HOSTNAME" 1>&2
+  IMG=$1              # jfroula/bbtools@sha256:
+  DB=$2               # /global/dna/shared/databases/jaws/refdata/
+  MOUNT=$3            # /refdata
+  SHELL_SCRIPT=$4     # /bin/bash
+  SCRIPT=$5           # script
+  
+  if [ $# -lt 5 ]; then
+      echo "One or more arguments are missing."
+      echo "Usage: $0 <docker image either tagged or sha@256> <path to refdata on nfs> <path to refdata in container> <path to bash> <script>"
+      exit 1
+  fi
+  
+  function pull_by_id() {
+      # This will:
+      # 1) check to see if it is cached already.
+      # 2) if not, figure out the right version to pull
+  
+      set -e
+      IMG=${1}
+      REPO=$(echo $IMG|sed 's/@.*//')
+      HASH=$(echo $IMG|sed 's/.*@//')
+      ID=$(echo $IMG|sed 's/.*://')
+  
+      # Try running it...
+      set +e
+      shifter --image=id:${ID} echo yes > /dev/null 2>&1 && return 0
+      set -e
+  
+      #Try to figure out the version to pull
+      RT=$(skopeo inspect docker://${IMG}|jq .RepoTags)
+      for ttag in $(echo $RT|sed 's/[",[]//g') ; do
+          digest=$(skopeo inspect docker://${REPO}:${ttag}|jq .Digest|sed 's/"//g')
+          if [ "$digest" == "$HASH" ] ; then
+              TAG=$ttag
+              break
+          fi
+      done
+      if [ -z $TAG ] ; then
+          echo "Unable to determine image version" 1>&2
+          exit 1
+      fi
+  
+      # Pull image by tag
+      shifterimg pull ${REPO}:${TAG} 1>&2
+  
+      # Get the ID
+      # All variables are global by default in bash so we can access the
+      # ID variable outside the function now.
+      ID=$(shifterimg lookup ${REPO}:${TAG})
+  }
+  
+  if [ $(echo ${IMG}|grep -c sha256) -gt 0 ] ; then
+          pull_by_id ${IMG}
+          ID=id:$ID
+  else
+          ID=$1
+  fi
+  
+  shifter --image=$ID -V $2:$3 $4 $5
+  EOM
+
   chgrp "$SITE_JTM_GROUP" "$INSTALL_DIR/shifter_exec.sh"
   chmod 775 "$INSTALL_DIR/shifter_exec.sh"
 
