Adding pool manager to shims

diff --git a/test/integration/deploy-supervisord b/test/integration/deploy-supervisord
--- a/test/integration/deploy-supervisord
+++ b/test/integration/deploy-supervisord
@@ -30,7 +30,7 @@ if [[ $RESULT -ne 0 ]]; then
   RESULT=0
   for VAR in $REQUIRED_VARS; do
     if [ -z ${!VAR+xxx} ]; then
-      echo "Missing env var: $VAR">&2
+      echo "Missing env var: $VAR" >&2
       RESULT=1
     fi
   done
@@ -58,8 +58,8 @@ function not_available() {
 not_available "supervisord" || pip install supervisor
 
 function generate_shim() {
-prog=$1
-cat <<EOM > $SUPERVISOR_DIR/bin/$prog
+  prog=$1
+  cat <<EOM >$SUPERVISOR_DIR/bin/$prog
 #!/bin/bash -l
 
 $SITE_LOAD_PYTHON
@@ -67,23 +67,23 @@ source $SUPERVISOR_DIR/venv/bin/activate
 
 exec $prog \$@
 EOM
-chmod +x $SUPERVISOR_DIR/bin/$prog
+  chmod +x $SUPERVISOR_DIR/bin/$prog
 }
 
 generate_shim supervisord
 generate_shim supervisorctl
 
 function fix_perms() {
-    local GROUP="$1"
-    local DIR="$2"
-    chmod -R 770 "$DIR"
-    chgrp -R "$GROUP" "$DIR"
-    find "$DIR" -type d -exec chmod g+s '{}' \;
+  local GROUP="$1"
+  local DIR="$2"
+  chmod -R 770 "$DIR"
+  chgrp -R "$GROUP" "$DIR"
+  find "$DIR" -type d -exec chmod g+s '{}' \;
 }
 
 fix_perms "$SITE_JTM_GROUP" "$SUPERVISOR_DIR"
 
-cat << EOM > $SUPERVISOR_DIR/supervisord-jaws.conf
+cat <<EOM >$SUPERVISOR_DIR/supervisord-jaws.conf
 [inet_http_server]
 port=0.0.0.0:$JAWS_SUPERVISOR_PORT
 username=jaws
@@ -143,15 +143,21 @@ startsecs=3
 startretries=10
 autorestart=unexpected
 
+[program:jaws-site-pool-manager-daemon]
+command=$SHIM_DIR/jaws-site-pool-manager-daemon-$DEPLOYMENT_NAME
+numprocs=1
+startsecs=3
+startretries=10
+autorestart=unexpected
+
 [group:jaws-$DEPLOYMENT_NAME]
-programs=jaws-site-run-daemon,jaws-site-transfer-daemon,jaws-site-perf-metrics-daemon,jaws-site-rpc
+programs=jaws-site-run-daemon,jaws-site-transfer-daemon,jaws-site-perf-metrics-daemon,jaws-site-rpc,jaws-site-pool-manager-daemon
 priority=999
 EOM
 
-
 ## BACKEND SUPERVISOR CONF
 
-cat << EOM > $SUPERVISOR_DIR/supervisord-cwl-backend.conf
+cat <<EOM >$SUPERVISOR_DIR/supervisord-cwl-backend.conf
 [inet_http_server]
 port=0.0.0.0:$JTM_SUPERVISOR_PORT
 username=jaws
diff --git a/test/integration/generate-shims b/test/integration/generate-shims
--- a/test/integration/generate-shims
+++ b/test/integration/generate-shims
@@ -38,13 +38,12 @@ if [[ $RESULT -ne 0 ]]; then
   RESULT=0
   for VAR in $REQUIRED_VARS; do
     if [ -z ${!VAR+xxx} ]; then
-      echo "Missing env var: $VAR">&2
+      echo "Missing env var: $VAR" >&2
       RESULT=1
     fi
   done
 fi
 [ $RESULT -eq 0 ] || exit 1
-
 
 ## WRITE SHIM SCRIPTS
 
@@ -56,7 +55,7 @@ FIX_PERMS_CLIENT=""
 [[ -n "$SITE_CLIENT_INSTALL_DIR" ]] && FIX_PERMS_CLIENT="fix_perms $SITE_CLIENT_GROUP $SITE_CLIENT_INSTALL_DIR"
 
 # transfer-daemon script
-cat <<EOM > $SHIM_DIR/jaws-site-transfer-daemon-$DEPLOYMENT_NAME
+cat <<EOM >$SHIM_DIR/jaws-site-transfer-daemon-$DEPLOYMENT_NAME
 #!/bin/bash -l
 
 function fix_perms() {
@@ -97,7 +96,7 @@ exec jaws-site --log $LOGS_DIR/site-transfer-daemon.log --config $CONFIG_DIR/jaw
 EOM
 
 # run-daemon script
-cat <<EOM > $SHIM_DIR/jaws-site-run-daemon-$DEPLOYMENT_NAME
+cat <<EOM >$SHIM_DIR/jaws-site-run-daemon-$DEPLOYMENT_NAME
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -109,7 +108,7 @@ exec jaws-site --log $LOGS_DIR/site-run-daemon.log --config $CONFIG_DIR/jaws-sit
 EOM
 
 # performance-metrics-daemon script
-cat <<EOM > $SHIM_DIR/jaws-site-perf-metrics-daemon-$DEPLOYMENT_NAME
+cat <<EOM >$SHIM_DIR/jaws-site-perf-metrics-daemon-$DEPLOYMENT_NAME
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -121,7 +120,7 @@ exec jaws-site --log $LOGS_DIR/site-perf-metrics-daemon.log --config $CONFIG_DIR
 EOM
 
 ## rpc shim script
-cat <<EOM > "$SHIM_DIR/jaws-site-rpc-$DEPLOYMENT_NAME"
+cat <<EOM >"$SHIM_DIR/jaws-site-rpc-$DEPLOYMENT_NAME"
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -133,8 +132,21 @@ source $SITE_VENV_DIR/bin/activate
 exec jaws-site --log $LOGS_DIR/site-rpc.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL rpc
 EOM
 
+## pool-manager shim script
+cat <<EOM >"$SHIM_DIR/jaws-site-pool-manager-$DEPLOYMENT_NAME"
+#!/bin/bash -l
+
+export LC_ALL=en_US.UTF-8
+export LANG=en_US.UTF-8
+export PYTHONIOENCODING=utf-8
+
+# START POOL MANAGER SERVER
+source $SITE_VENV_DIR/bin/activate
+exec jaws-site --log $LOGS_DIR/site-pool-manager.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL pool_manager
+EOM
+
 ## jtm shim script
-cat <<EOM > "$SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME"
+cat <<EOM >"$SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME"
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -168,7 +180,7 @@ EOM
 # Otherwise we need to know the location of the script which may not be best practice
 
 ## parsl-recv shim script
-cat <<EOM > "$SHIM_DIR/jaws-parsl-recv-$DEPLOYMENT_NAME"
+cat <<EOM >"$SHIM_DIR/jaws-parsl-recv-$DEPLOYMENT_NAME"
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
