comment out set -e

diff --git a/test/integration/deploy-jaws b/test/integration/deploy-jaws
--- a/test/integration/deploy-jaws
+++ b/test/integration/deploy-jaws
@@ -1,6 +1,8 @@
 #!/bin/bash -l
 
-set -e
+# comment out set -e because this breaks the deployment to tahoma
+# because the chgrp command in test/integration/define-env fails for /big_scratch/singularity_files
+#set -e
 
 echo "BEGIN deploy-jaws"
 
