Fixed shifter pull setup

diff --git a/test/integration/deploy-cromwell b/test/integration/deploy-cromwell
--- a/test/integration/deploy-cromwell
+++ b/test/integration/deploy-cromwell
@@ -74,35 +74,46 @@ if [[ "$SITE_CONTAINER_TYPE" == "shifter" ]]; then
     CONTAINER_PULL="
     REPO=\$(echo \${docker} | sed 's/@.*//')
     HASH=\$(echo \${docker} | sed 's/.*@//')
+    ID=\$(echo \${docker} | sed 's/.*://')
+    IMAGE=\${docker}
     TAG=
 
     if [[ \$HASH =~ \"sha256\" ]]; then
-        #Try to figure out the version to pull
-        RT=\$(skopeo inspect docker://\${docker} | jq .RepoTags)
-        if [[ \$(echo \$RT | grep \"Error\" ) ]]; then
-            echo \"Failed to run skopeo for \$docker!\"
-            echo \"Error: \$RT.\"
-            exit 1
-        else
-            echo \"successfully pulled image \$IMAGE!\"
-        fi
-        for ttag in \$(echo \$RT | sed 's/[\",[]//g'); do
-            digest=\$(skopeo inspect docker://\$REPO:\$ttag | jq .Digest | sed 's/\"//g')
-            if [ \"\$digest\" == \"\$HASH\" ]; then
-                TAG=\$ttag
-                break
-            fi
-        done
-
-        if [ -z \$TAG ]; then
-            echo \"Unable to determine image version.\" 1>&2
-            exit 1
-        fi
-
-        IMAGE=\$REPO:\$TAG
+         shifter --image=id:\$ID echo testing to see if we already have image > /dev/null 2>&1
     else
-        IMAGE=\$REPO
+         shifter --image=\${docker} echo testing to see if we already have image > /dev/null 2>&1
     fi
+
+    if [[ \$? == 0 ]]; then
+        echo \"image already pulled: \${docker}.\"
+    else
+      if [[ \$HASH =~ \"sha256\" ]]; then
+          #Try to figure out the version to pull
+          RT=\$(skopeo inspect docker://\${docker} | jq .RepoTags)
+          if [[ \$(echo \$RT | grep \"Error\" ) ]]; then
+              echo \"Failed to run skopeo for \$docker!\"
+              echo \"Error: \$RT.\"
+              exit 1
+          else
+              echo \"successfully pulled image \$IMAGE!\"
+          fi
+          for ttag in \$(echo \$RT | sed 's/[\",[]//g'); do
+              digest=\$(skopeo inspect docker://\$REPO:\$ttag | jq .Digest | sed 's/\"//g')
+              if [ \"\$digest\" == \"\$HASH\" ]; then
+                  TAG=\$ttag
+                  break
+              fi
+          done
+
+          if [ -z \$TAG ]; then
+              echo \"Unable to determine image version.\" 1>&2
+              exit 1
+          fi
+
+          IMAGE=\$REPO:\$TAG
+      else
+          IMAGE=\$REPO
+      fi
 
     # Pull image by tag
     out=\$(shifterimg pull \$IMAGE 2>&1)
