Fix syntax error
Closes #907

cromwell.conf is missing a closing brace which results in a syntax error
from Cromwell.

diff --git a/test/integration/deploy-cromwell b/test/integration/deploy-cromwell
--- a/test/integration/deploy-cromwell
+++ b/test/integration/deploy-cromwell
@@ -71,7 +71,7 @@ if [[ "$SITE_CONTAINER_TYPE" == "shifter" ]]; then
   CONTAINER_EXPORT="out=\$(shifterimg lookup \${docker} || shifterimg pull \${docker})
 ret=\$?
 if [[ \$ret != 0 || \$(echo \$out | grep \"FAILURE\") ]]; then
-  echo \"Invalid container name or failed to pull container, \${docker!\" >&2
+  echo \"Invalid container name or failed to pull container, \${docker}!\" >&2
   exit \$ret
 else
   echo \"Successfully pulled \${docker}!\"
