Resolve "Create Pool manager Daemon"

diff --git a/test/integration/generate-shims b/test/integration/generate-shims
--- a/test/integration/generate-shims
+++ b/test/integration/generate-shims
@@ -37,13 +37,12 @@ if [[ $RESULT -ne 0 ]]; then
   RESULT=0
   for VAR in $REQUIRED_VARS; do
     if [ -z ${!VAR+xxx} ]; then
-      echo "Missing env var: $VAR">&2
+      echo "Missing env var: $VAR" >&2
       RESULT=1
     fi
   done
 fi
 [ $RESULT -eq 0 ] || exit 1
-
 
 ## WRITE SHIM SCRIPTS
 
@@ -55,7 +54,7 @@ FIX_PERMS_CLIENT=""
 [[ -n "$SITE_CLIENT_INSTALL_DIR" ]] && FIX_PERMS_CLIENT="fix_perms $SITE_CLIENT_GROUP $SITE_CLIENT_INSTALL_DIR"
 
 # transfer-daemon script
-cat <<EOM > $SHIM_DIR/jaws-site-transfer-daemon-$DEPLOYMENT_NAME
+cat <<EOM >$SHIM_DIR/jaws-site-transfer-daemon-$DEPLOYMENT_NAME
 #!/bin/bash -l
 
 function fix_perms() {
@@ -96,7 +95,7 @@ exec jaws-site --log $LOGS_DIR/site-transfer-daemon.log --config $CONFIG_DIR/jaw
 EOM
 
 # run-daemon script
-cat <<EOM > $SHIM_DIR/jaws-site-run-daemon-$DEPLOYMENT_NAME
+cat <<EOM >$SHIM_DIR/jaws-site-run-daemon-$DEPLOYMENT_NAME
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -108,7 +107,7 @@ exec jaws-site --log $LOGS_DIR/site-run-daemon.log --config $CONFIG_DIR/jaws-sit
 EOM
 
 # performance-metrics-daemon script
-cat <<EOM > $SHIM_DIR/jaws-site-perf-metrics-daemon-$DEPLOYMENT_NAME
+cat <<EOM >$SHIM_DIR/jaws-site-perf-metrics-daemon-$DEPLOYMENT_NAME
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -120,7 +119,7 @@ exec jaws-site --log $LOGS_DIR/site-perf-metrics-daemon.log --config $CONFIG_DIR
 EOM
 
 ## rpc shim script
-cat <<EOM > "$SHIM_DIR/jaws-site-rpc-$DEPLOYMENT_NAME"
+cat <<EOM >"$SHIM_DIR/jaws-site-rpc-$DEPLOYMENT_NAME"
 #!/bin/bash -l
 
 export LC_ALL=en_US.UTF-8
@@ -131,5 +130,70 @@ export PYTHONIOENCODING=utf-8
 source $SITE_VENV_DIR/bin/activate
 exec jaws-site --log $LOGS_DIR/site-rpc.log --config $CONFIG_DIR/jaws-site.conf --log-level $LOG_LEVEL rpc
 EOM
+
+## pool-manager shim script
+cat <<EOM >"$SHIM_DIR/jaws-site-pool-manager-$DEPLOYMENT_NAME"
+#!/bin/bash -l
+
+export LC_ALL=en_US.UTF-8
+export LANG=en_US.UTF-8
+export PYTHONIOENCODING=utf-8
+
+# START POOL MANAGER SERVER
+source $SITE_VENV_DIR/bin/activate
+export CONDOR_CONFIG=$CONFIG_DIR/condor_central.config
+exec jaws-condor --log $LOGS_DIR/jaws-condor-pool-manager.log --config $CONFIG_DIR/jaws_condor.conf --log-level $LOG_LEVEL
+EOM
+
+## jtm shim script
+cat <<EOM >"$SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME"
+#!/bin/bash -l
+
+export LC_ALL=en_US.UTF-8
+export LANG=en_US.UTF-8
+export PYTHONIOENCODING=utf-8
+
+test -d $SITE_JTM_SCRATCH_DIR || mkdir $SITE_JTM_SCRATCH_DIR
+chgrp $SITE_JTM_GROUP $SITE_JTM_SCRATCH_DIR
+chgrp $SITE_JTM_GROUP $SITE_INPUTS_DIR
+chmod 2770 $SITE_JTM_SCRATCH_DIR
+
+# DEPLOY TO NFS DIR
+# HACK: see .gitlab-ci.yml for the explanation of why that copy does not happen in the CI directly
+
+#test -d $JTM_VENV_DIR || mkdir -p $JTM_VENV_DIR
+#chmod 2770 $JTM_VENV_DIR
+
+#cp $CONFIG_DIR/jaws-jtm.conf $CONFIG_DIR/
+#chgrp $SITE_JTM_GROUP $JTM_CONFIG_FILE
+#chmod 0640 $CONFIG_DIR/jaws-jtm.conf
+
+# RUN JTM
+
+source $JTM_VENV_DIR/bin/activate
+export JTM_CONFIG_FILE=$JTM_CONFIG_FILE
+
+exec jtm --config=$CONFIG_DIR/jaws-jtm.conf --debug manager -ld $LOGS_DIR
+EOM
+
+# TODO: Need to create executable scripts for running recv.py
+# Otherwise we need to know the location of the script which may not be best practice
+
+## parsl-recv shim script
+cat <<EOM >"$SHIM_DIR/jaws-parsl-recv-$DEPLOYMENT_NAME"
+#!/bin/bash -l
+
+export LC_ALL=en_US.UTF-8
+export LANG=en_US.UTF-8
+export PYTHONIOENCODING=utf-8
+
+source $INSTALL_DIR/parsl/bin/activate
+exec jaws-parsl-recv --config=$CONFIG_DIR/parsl.ini
+EOM
+
+## SET PERMISSIONS
+chgrp "$SITE_JTM_GROUP" "$SHIM_DIR/jaws-jtm-$DEPLOYMENT_NAME"
+chgrp "$SITE_JTM_GROUP" "$SHIM_DIR/jaws-parsl-recv-$DEPLOYMENT_NAME"
+chmod +x "$SHIM_DIR"/*
 
 printf "END generate-shims\n\n"
